### ISSUE TITLE
Can't create Docker server for Open Liberty image

### ISSUE THREAD

**Issue by eharris369** [OpenLiberty/open-liberty-tools#133]
A Docker server cannot be created for the Open Liberty Docker image.  This is because the code is looking for the server to be in /opt/ibm/wlp when it is in /opt/ol/wlp.

**Comment by yeekangc** [comment]
@eharris369, can you confirm that OLT alone has support for Docker i.e. no dependencies on WDT?  Just that we have this bug here.

Thank you.
