### ISSUE TITLE
Add CDI 2.0 support to Open Liberty Tools (JSR 365)

### ISSUE THREAD

**Issue by johnmcollier** [OpenLiberty/open-liberty-tools#21]
A number of classes in Open Liberty Tools need to be updated to add CDI 2.0 support and to accommodate CDI 2.0 support in the Open Liberty runtime. 

A list of components (but not exhaustive) that have files that need to be updated are:
- com.ibm.ws.st.core
- com.ibm.ws.st.jee.core

**Comment by eharris369** [comment]
This was covered under issue #145.
