### ISSUE TITLE
Tools are breaking Eclipse single-root rules for Web Projects

### ISSUE THREAD

**Issue by epomatti** [OpenLiberty/open-liberty-tools#308]
After installing the tools in Eclipse my Web Projects are issuing the following warnings and conflicting with Eclipse validations.

```
Description	Resource	Path	Location	Type
Broken single-root rule: Only one <wb-resource> element with a deploy path of "/" is allowed for a web project or an EAR project	org.eclipse.wst.common.component	/libertymq/.settings	Unknown	Project Structure Marker
```
and

```
Description	Resource	Path	Location	Type
Broken single-root rule: The output folder for a web project must be <root folder>/WEB-INF/classes	libertymq		Unknown	Project Structure Marker
```

To reproduce the issue simply install latest tools in Eclipse and create a maven Web Project with war type.

![image](https://user-images.githubusercontent.com/6530769/56915566-40b44600-6a8d-11e9-8005-2fe2a746a05a.png)

**Comment by lentheivendra** [comment]
Hello, the "The output folder for a web project must be <root folder>/WEB-INF/classes" warning will not be shown if the project is targeted to a Liberty server.  Both of these validation messages come from the Open Liberty Tools' project structure validator.

Although these are warnings that can be ignored, if you want them to not show up, then the validator can be disabled by going to the menu item Windows -> Preferences -> Validation and unchecking the 'Project Structure Validator'.  But this will also disable other validations that particular validator does to check project structure.

**Comment by epomatti** [comment]
Nice, it worked once I targeted the project to the Liberty Server. Thanks.
