### ISSUE TITLE
Cannot find dependency 'com.ibm.ws.ffdc' for com.ibm.ws.kernel.feature.resolver 1.0.28.201905010001

### ISSUE THREAD

**Issue by josephca** [OpenLiberty/open-liberty-tools#312]
OLT install on Eclipse 2019-03 failed with the following message. The recent 'com.ibm.ws.kernel.feature.resolver.jar' has a missing dependency. 

Cannot complete the install because one or more required items could not be found.
  Software being installed: WebSphere® Application Server Liberty Tools 19.0.6.v2019-05-03_0903 (com.ibm.ws.st.liberty.tools.feature.group 19.0.6.v2019-05-03_0903)
  Missing requirement: Liberty Feature Resolver 1.0.28.201905010001 (com.ibm.ws.kernel.feature.resolver 1.0.28.201905010001) requires 'java.package; com.ibm.ws.ffdc [1.0.0,2.0.0)' but it could not be found
  Cannot satisfy dependency:
    From: WebSphere® Application Server Liberty Tools 1.0.906.v2019-05-03_0903 (com.ibm.ws.st.core 1.0.906.v2019-05-03_0903)
    To: java.package; com.ibm.ws.kernel.feature 0.0.0
  Cannot satisfy dependency:
    From: WebSphere® Application Server Liberty Tools 1.0.5.v2019-05-03_0903 (com.ibm.ws.st.liberty.tools.base.feature.group 1.0.5.v2019-05-03_0903)
    To: org.eclipse.equinox.p2.iu; com.ibm.ws.st.core [1.0.906.v2019-05-03_0903,1.0.906.v2019-05-03_0903]
  Cannot satisfy dependency:
    From: WebSphere® Application Server Liberty Tools 19.0.6.v2019-05-03_0903 (com.ibm.ws.st.liberty.tools.feature.group 19.0.6.v2019-05-03_0903)
    To: org.eclipse.equinox.p2.iu; com.ibm.ws.st.liberty.tools.base.feature.group [1.0.5.v2019-05-03_0903,1.0.5.v2019-05-03_0903]

**Comment by eharris369** [comment]
Opened runtime defect: https://github.ibm.com/was-liberty/WS-CD-Open/issues/16816

**Comment by GeekArthur** [comment]
Thanks @eharris369 open issue against liberty runtime, also @josephca FYI, for plugin `com.ibm.ws.kernel.feature.resolver`, we pull it from DHE. Reference is here: https://apps.na.collabserv.com/wikis/home?lang=en-us#!/wiki/Wadb7253d6d74_4520_94f1_4860bfae905d/page/Pre-release%20activities

**Comment by eharris369** [comment]
I pinged Marika about the runtime defect (https://github.ibm.com/was-liberty/WS-CD-Open/issues/16816) as well as the other runtime defect that is open for install on Oxygen (https://github.ibm.com/was-liberty/WS-CD-Open/issues/16308) and she has asked Andy McCright to have a look at them.

**Comment by josephca** [comment]
Verified the fix.
