### ISSUE TITLE
High CPU load causes Liberty Tools to terminate the server

### ISSUE THREAD

**Issue by eharris369** [OpenLiberty/open-liberty-tools#350]
The tools ask the server for its status periodically to make sure the status showing is correct.  If there is high CPU load the server status command can time out.  In this case the tools think the server is stopped and so terminate the launch associated with the server.  Part of the problem is the method called to get the status, WebSphereRuntime.isServerStarted only returns true or false.  The following should be done:

1. Increase the timeout for the server status command as it is low
2. Change the method called to return exactly what happened - running, stopped, or timeout (if there is an error, it already throws an exception)
3. If the server status times out, don't terminate the launch, instead check the process associated with the launch, if it is still going then loop around and try the server status again (after the time delay)
4. Log any timeouts (this would have been useful in diagnosing this)

**Comment by eharris369** [comment]
PR created for this issue: https://github.com/OpenLiberty/open-liberty-tools/pull/351

**Comment by josephca** [comment]
@eharris369 Can we close this?  as #351 is merged already.

**Comment by eharris369** [comment]
Closing as this is fixed.
