### ISSUE TITLE
Discussion about activity in this project

### ISSUE THREAD

**Issue by c-koell** [OpenLiberty/open-liberty-tools#374]
Hi ..

Unfortunately the support in this project does not work really. The support in the project open-liberty (http://github.com/OpenLiberty/open-liberty/) on the other hand, it works great.

On some issues there are no responses for weeks to months.

What about the new project lead @theshovon ? Sorry for my words but i think it should be possible to give some response on long open issues ...

What about a release plan ? In the really active open-liberty project there are every month releases.
The issue #348 was opened in november 2019 ! We still wait for a release to use the new maven plugin.

Thanks in advance for any feedback and i hope that someone at IBM feels more responsible for this project in the future !

Just one more word .. i think the eclipse plugin is great but as described it is not really maintained.

Thanks in advance for any feedback

**Comment by josephca** [comment]
Hi @c-koell, 
I see your disappointment here, however, we're certainly monitoring the issues even though it's a slow pace. 
In addition,  #348 will be handled by a developer soon. 

Thanks in advance for your patience.

**Comment by josephca** [comment]
OLT 20.0.0.3 is released with the fix for  #348. 
Closing it now. Please reopen if you disagree. Thanks!
