### ISSUE TITLE
Failed to execute goal net.wasdev.wlp.maven.plugins:liberty-maven-plugin:2.6.1:package-server (package-server) on project

### ISSUE THREAD

**Issue by WaveRider52** [OpenLiberty/open-liberty-tools#415]
I ran two times docker build command, seen below

C:\Users\OrcunOdabas\git\CICemployeelocation>docker build -t emploc1.0 . > docker-build.log
The command '/bin/sh -c ./mvnw install' returned a non-zero code: 1

C:\Users\OrcunOdabas\git\CICemployeelocation>docker build -t emploc1.0 . > docker-build2.log
The command '/bin/sh -c ./mvnw install' returned a non-zero code: 1

And each time it failed with the same error:
############   Server defaultServer package failed. It must be stopped before it can be packaged.  #######
`[INFO] CWWKM2144I: Update server configuration file bootstrap.properties from inlined configuration.
[INFO] CWWKM2136I: Package file location is /app/target/cicemployeelocation-1.0-SNAPSHOT.zip.
[INFO] CWWKM2001I: server.config.dir is /app/target/liberty/wlp/usr/servers/defaultServer.
[INFO] CWWKM2001I: server.output.dir is /app/target/liberty-alt-output-dir/defaultServer.
[INFO] CWWKM2001I: Invoke command is [/app/target/liberty/wlp/bin/server, package, defaultServer, --archive=/app/target/cicemployeelocation-1.0-SNAPSHOT.zip, --include=usr].
[INFO] 
[INFO] Packaging server defaultServer.
[INFO] Server defaultServer is running.
[INFO] Server defaultServer package failed. It must be stopped before it can be packaged.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 05:22 min
[INFO] Finished at: 2021-02-10T22:32:46Z
[INFO] Final Memory: 46M/253M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal net.wasdev.wlp.maven.plugins:liberty-maven-plugin:2.6.1:package-server (package-server) on project cicemployeelocation: CWWKM2002E: Failed to invoke [/app/target/liberty/wlp/bin/server, package, defaultServer, --archive=/app/target/cicemployeelocation-1.0-SNAPSHOT.zip, --include=usr]. RC= 3 but expected=[0]. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException`
######################

Another mate run the same command but at his machine -my guess is that liberty server is not started during the build process. Below for your comparison the same lines of his logs:

###### Log of Mate, where docker build run successfully  ######
`[INFO] --- liberty-maven-plugin:2.6.1:package-server (package-server) @ cicemployeelocation ---
[INFO] CWWKM2102I: Using artifact based assembly archive : com.ibm.websphere.appserver.runtime:wlp-webProfile7:null:21.0.0.1:zip.
[INFO] CWWKM2102I: Using installDirectory : /app/target/liberty/wlp.
[INFO] CWWKM2102I: Using serverName : defaultServer.
[INFO] CWWKM2102I: Using serverDirectory : /app/target/liberty/wlp/usr/servers/defaultServer.
[INFO] CWWKM2112I: Re-using previously installed assembly.
[INFO] CWWKM2134I: Packaging server defaultServer.
[INFO] Copying 1 file to /app/target/liberty/wlp/usr/servers/defaultServer
[INFO] Copying 1 file to /app/target/liberty/wlp/usr/servers/defaultServer
[INFO] CWWKM2144I: Update server configuration file server.xml from /app/src/main/liberty/config/server.xml.
[INFO] CWWKM2144I: Update server configuration file jvm.options from /app/src/main/liberty/config/jvm.options.
[INFO] CWWKM2144I: Update server configuration file bootstrap.properties from inlined configuration.
[INFO] CWWKM2136I: Package file location is /app/target/cicemployeelocation-1.0-SNAPSHOT.zip.
[INFO] CWWKM2001I: server.config.dir is /app/target/liberty/wlp/usr/servers/defaultServer.
[INFO] CWWKM2001I: server.output.dir is /app/target/liberty-alt-output-dir/defaultServer.
[INFO] CWWKM2001I: Invoke command is [/app/target/liberty/wlp/bin/server, package, defaultServer, --archive=/app/target/cicemployeelocation-1.0-SNAPSHOT.zip, --include=usr].
[INFO] 
[INFO] Packaging server defaultServer.
[INFO] Server defaultServer package complete in /app/target/cicemployeelocation-1.0-SNAPSHOT.zip.
[INFO] 
[INFO] --- liberty-maven-plugin:2.6.1:test-start-server (test-start-server) @ cicemployeelocation ---
[INFO] CWWKM2102I: Using artifact based assembly archive : com.ibm.websphere.appserver.runtime:wlp-webProfile7:null:21.0.0.1:zip.
[INFO] CWWKM2102I: Using installDirectory : /app/target/liberty/wlp.
[INFO] CWWKM2102I: Using serverName : defaultServer.
[INFO] CWWKM2102I: Using serverDirectory : /app/target/liberty/wlp/usr/servers/defaultServer.
[INFO] CWWKM2112I: Re-using previously installed assembly.
[INFO] Copying 1 file to /app/target/liberty/wlp/usr/servers/defaultServer
[INFO] Copying 1 file to /app/target/liberty/wlp/usr/servers/defaultServer
[INFO] CWWKM2144I: Update server configuration file server.xml from /app/src/main/liberty/config/server.xml.
[INFO] CWWKM2144I: Update server configuration file jvm.options from /app/src/main/liberty/config/jvm.options.
[INFO] CWWKM2144I: Update server configuration file bootstrap.properties from inlined configuration.
[INFO] CWWKM2001I: server.config.dir is /app/target/liberty/wlp/usr/servers/defaultServer.
[INFO] CWWKM2001I: server.output.dir is /app/target/liberty/wlp/usr/servers/defaultServer.
[INFO] CWWKM2001I: Invoke command is [/app/target/liberty/wlp/bin/server, start, defaultServer].
[INFO] 
[INFO] Starting server defaultServer.
[INFO] Server defaultServer started with process ID 271.
[INFO] Waiting up to 30 seconds for server confirmation:  CWWKF0011I to be found in /app/target/liberty/wlp/usr/servers/defaultServer/logs/messages.log`
#######################################################

I'have also found that issue I'm facing was reported: https://github.com/OpenLiberty/guide-microprofile-config/issues/7

But the solution (<outputDirectory>/tmp/liberty</outputDirectory>) for issue #7 was already adapted in my pom.xml (as seen on snippet below):

`  <profile>
            <id>bx-dev-build</id>
            <build>
                <pluginManagement>
                    <plugins>
                        <plugin>
                            <groupId>net.wasdev.wlp.maven.plugins</groupId>
                            <artifactId>liberty-maven-plugin</artifactId>
                            <version>${liberty.plugin.version}</version>
                            <configuration>
                                <outputDirectory>/tmp/liberty</outputDirectory>
                            </configuration>
                            <executions>
                                <execution>
                                    <id>install-feature</id>
                                    <phase>prepare-package</phase>
                                    <goals>
                                        <goal>install-feature</goal>
                                    </goals>
                                    <configuration>
                                        <outputDirectory>/tmp/liberty</outputDirectory>
                                    </configuration>
                                </execution>
                                <execution>
                                    <id>package-server</id>
                                    <phase>package</phase>
                                    <goals>
                                        <goal>package-server</goal>
                                    </goals>
                                    <configuration>
                                        <outputDirectory>/tmp/liberty</outputDirectory>
                                    </configuration>
                                </execution>
                            </executions>
                        </plugin>
                    </plugins>
                </pluginManagement>
             </build>
        </profile>`
		
So I cant figure out what the reason is. Thanks for your help. Orçun

**Comment by mattcolegate** [comment]
Hi @WaveRider52, 
This repo is for Open Liberty Tools, the Eclipse-based tools for developing and deploying your applications onto Open Liberty. I don't think we run on Docker, because we're a set of plugins for an IDE, so this has probably been raised in the wrong repo. Can you give me more background as to what it is you're trying to do, or maybe a link to some instructions that you're following, and we'll see if we can get you to the right place to deal with your problem.

**Comment by mattcolegate** [comment]
Based on the logs you've provided, it looks like there's some trouble with `liberty-maven-plugin` so you might like to try the team at https://github.com/OpenLiberty/ci.maven

**Comment by WaveRider52** [comment]
Hi Matt,
I agree with you that my issue is placed on wrong repo. Thank you for your reply and advise to try by ci.maven team. Thanks and Regards, Orçun

**Comment by mattcolegate** [comment]
Thanks @WaveRider52 , I'll mark this issue closed then.

**Comment by iamjay** [comment]
@WaveRider52 I'm having the same issue. Have you managed to solve this?
