### ISSUE TITLE
Open Liberty Does not show up in Servers view in Eclipse

### ISSUE THREAD

**Issue by cwhankey** [OpenLiberty/open-liberty-tools#426]
I installed Liberty Developer Tools 21.0.0.3 in Eclipse 2021-03 & the install was successful, but there is no IBM node in the servers view.  Any suggestions on how to resolve this?

![servers view Eclipse IDE](https://user-images.githubusercontent.com/10787463/121789057-af3abc00-cba0-11eb-9ecb-0c378b83ea9b.png)

**Comment by cwhankey** [comment]
Here is some additional info:

Eclipse IDE for Java Developers - The open-liberty-tools show up fine in this  version of  Eclipse 2021-03 

Eclipse IDE for Enterprise Java and Web Developers - The open-liberty-tools do not show up in this version of  Eclipse 2021-03

**Comment by mattcolegate** [comment]
Are you the same person as https://stackoverflow.com/questions/67911003/ibm-liberty-developer-tools-not-showing-up-in-eclipse/?

**Comment by cwhankey** [comment]
yes, that is me.

**Comment by mattcolegate** [comment]
I see you accepted the answer there, so I'll close this issue.
