### ISSUE TITLE
OpenLiberty cannot run the war project with Servlet 5.0  (Jakarta EE 9.1 and MicroProfile 5.0)  in Eclipse IDE 2022-09

### ISSUE THREAD

**Issue by RuiBaiXYZ** [OpenLiberty/open-liberty-tools#463]
**OS**
$ cat /etc/rocky-release

> Rocky Linux release 9.0 (Blue Onyx)

**JDK**
$ echo $JAVA_HOME

> /usr/java/jdk-17.0.4.1+1

$ java --version

> java 17.0.4.1 2022-08-12
> IBM Semeru Runtime Certified Edition 17.0.4.1 (build 17.0.4.1+1)
> Eclipse OpenJ9 VM 17.0.4.1 (build openj9-0.33.1, JRE 17 Linux amd64-64-Bit Compressed References 20220812_206 (JIT enabled, AOT enabled)
> OpenJ9   - 1d9d16830
> OMR      - b58aa2708
> JCL      - df9b7169bff based on jdk-17.0.4.1+1)

**Eclipse**

> Eclipse IDE for Enterprise Java and Web Developers (includes Incubating components)
> 
> Version: 2022-09 (4.25.0)
> Build id: 20220908-1902

**OpenLiberty**

> Open Liberty Version 22.0.0.11 - (22.0.0.11-202210101601)

**OpenLiberty Tools**

> openlibertytools-22.2.v2022-08-02_1446.zip
> https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/tools/nightly/2022-08-02_1446/openlibertytools-22.2.v2022-08-02_1446.zip

**ERROR**
web.xml

```
<web-app xmlns="https://jakarta.ee/xml/ns/jakartaee"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="https://jakarta.ee/xml/ns/jakartaee
         web-app_5_0.xsd"
  version="5.0">
...
```

When adding project to OpenLiberty Server , the following error occured.
 The server does not support version 5.0 of the J2EE Web module specification. 

By now , I'm not sure that was caused by Eclipse IDE , nor by OpenLiberty Tools.
Eclise community already had a ticket : https://bugs.eclipse.org/bugs/show_bug.cgi?id=579533

And also , have a question,
 will https://github.com/OpenLiberty/open-liberty-tools be replaced by https://github.com/OpenLiberty/liberty-tools-eclipse in the future.

thanks~

**Comment by mattcolegate** [comment]
Hi @RuiBaiXYZ,

I'm afraid there's no plans to support Jakarta EE 9.1 in Open Liberty Tools at this time. I believe Liberty Tools https://github.com/OpenLiberty/liberty-tools-eclipse does have some support, but check with them. I can confirm that there are no plans to replace Open Liberty Tools with Liberty Tools at this time.
