### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by titou10titou10** [OpenLiberty/open-liberty-tools#471]
The last official release is now months away, and if you want to use it you need to use a version of Eclipse that is older than one year...

So the question are:
- is this project dead?
- Do we have to move to use the  [Tools for Eclipse IDE project](https://github.com/OpenLiberty/liberty-tools-eclipse) plugin in order to develop with the latests version of Eclipse and OpenLiberty?

**Comment by mattcolegate** [comment]
Hi @titou10titou10,

This project is not dead - the last merged PR was last month. We now release on a biannual cadence in line with LDT and WDT (https://www.ibm.com/support/pages/node/6559708). Our next release is due at the end of May.
You do not have to move to the Tools for Eclipse IDE project, but if you are looking to work with Jakarta EE 9.x APIs or MicroProfile APIs then [our next-generation open source development tools](https://marketplace.eclipse.org/content/liberty-tools) might well prove a better fit. You can also help shape the future of these tools by providing feedback or contributing on [GitHub](https://github.com/OpenLiberty/liberty-tools-eclipse).
