### ISSUE TITLE
Support creating the runtime and server on import of a Gradle project

### ISSUE THREAD

**Issue by eharris369** [OpenLiberty/open-liberty-tools#53]
When the user imports a Gradle project that has Liberty integration they should be prompted to create the runtime and server.

**Comment by keithchong** [comment]
Hi @eharris369, I have one part of the scenario working.  It is the case where the imported project is already **pre-built** and the Gradle build folder already contains wlp and the plugin config xml file exists.  I demoed this last week and the dialog came up.   Elson mentioned yesterday that if there is an equivalent Gradle life-cycle step/stage where upon import, the project is 'built' automatically by the liberty Gradle plugin (perhaps hooking in with the Gradle tools or buildship), then I _don't_ think we have to do anything more except for tweaking the conditions for which we should prompt.  If there is no Gradle-equivalent, then we must do something extra to get the Gradle project to build automatically.   The conditions might be 1) It must be a Gradle project 2) We might have to scan the build.gradle file for something 'liberty' specific, like, it applies the liberty plugin, or something.

**Comment by eharris369** [comment]
This is done.
