### ISSUE TITLE
Respond to any changes in the Gradle liberty-plugin-config.xml

### ISSUE THREAD

**Issue by eharris369** [OpenLiberty/open-liberty-tools#57]
Listen for changes to the liberty-plugin-config.xml file and respond appropiately.

**Comment by keithchong** [comment]
Hi @eharris369, what changes do you have in mind about this one?  The file is derived/generated and should not be edited?

**Comment by eharris369** [comment]
Hi @keithchong, if the user changes something in the project and does a build that causes a change in liberty-plugin-config.xml then the tools need to react to this.  I think that most or even all of it will be free thanks to the common code but it needs to be investigated to make sure.  There should already be code that listens to changes on this file.

**Comment by eharris369** [comment]
This is done.
