### ISSUE TITLE
Build Gradle project on import

### ISSUE THREAD

**Issue by eharris369** [OpenLiberty/open-liberty-tools#62]
If a Gradle project is imported make sure it is built and the liberty-plugin-config.xml file is generated if the project has Liberty integration.

-> This may not be needed if the ecosystem tools can do the build

**Comment by keithchong** [comment]
From what I see, I don't think there is anything in Buildship that ecosystem tools can hook into.  Buildship provides the Import wizard.

**Comment by eharris369** [comment]
This was done by the the Liberty Gradle plugin.
