### ISSUE TITLE
Running the create server and runtime action results in Scan Job being scheduled...

### ISSUE THREAD

**Issue by keithchong** [OpenLiberty/open-liberty-tools#73]
Looks like the Scan Job is scheduled on 'any' workspace resource change with project deltas.

However, we know that when the Create server and runtime  action is selected on the build type (eg. Maven) then a new project folder is created, at least.  If this is the only thing that results in a workspace resource change, then the LibertyManager could be more refined and not trigger another ScanJob. 

This issue is opened to investigate whether LibertyManager can be made smarter and not start the scan job when our own runtime project is created.   (eg. check the event source if it is 'us')

The action results in at least two resource deltas.  One on the build plugin project and one on the new runtime project, and both resulted in new Scan Jobs.

**Comment by eharris369** [comment]
Closing as this is fixed by PR #104
